# .github/workflows/tests.yml
name: tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      # 1) checkout
      - uses: actions/checkout@v4

      # 2) Python + cache
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      # 3) install project + test deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"           # defined in pyproject.toml
          pip install pytest pytest-cov

      # 4) run tests & create coverage.xml
      - name: Run tests
        run: pytest --cov=llm_prompt_builders --cov-report=xml

      # 5) upload to Codecov         ##########################################
      - name: Upload coverage
        if: success() && env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
          fail_ci_if_error: true        # keeps the job red if upload fails
